insert into course (course_num,dept_code,title,credits) values ('BRI306','3952','nonummy maecenas',5);
insert into course (course_num,dept_code,title,credits) values ('LTQ006','3448','lobortis',5);
insert into course (course_num,dept_code,title,credits) values ('OZU974','3952','fusce congue diam',3);
insert into course (course_num,dept_code,title,credits) values ('DXQ633','4138','amet eros suspendisse',5);
insert into course (course_num,dept_code,title,credits) values ('MVF839','4510','cum sociis natoque',4);
insert into course (course_num,dept_code,title,credits) values ('EPG843','1300','quam nec',4);
insert into course (course_num,dept_code,title,credits) values ('MKJ441','4510','id',3);
insert into course (course_num,dept_code,title,credits) values ('KKO305','6881','ultrices posuere cubilia',2);
insert into course (course_num,dept_code,title,credits) values ('PPC248','8946','suspendisse potenti',2);
insert into course (course_num,dept_code,title,credits) values ('STR413','1465','hac',4);
insert into course (course_num,dept_code,title,credits) values ('OLM203','4138','elit proin',3);
insert into course (course_num,dept_code,title,credits) values ('EPW314','0393','id lobortis convallis',5);
insert into course (course_num,dept_code,title,credits) values ('LMH532','6857','posuere cubilia curae',1);
insert into course (course_num,dept_code,title,credits) values ('JVG569','0078','sed',1);
insert into course (course_num,dept_code,title,credits) values ('XRX934','2250','nisi eu orci',4);
insert into course (course_num,dept_code,title,credits) values ('MNU873','0393','accumsan',5);
insert into course (course_num,dept_code,title,credits) values ('YSO505','4510','ligula pellentesque ultrices',4);
insert into course (course_num,dept_code,title,credits) values ('FGW555','2250','tellus',2);
insert into course (course_num,dept_code,title,credits) values ('UFC982','3952','nibh in quis',4);
insert into course (course_num,dept_code,title,credits) values ('QUC181','6881','integer pede',2);
insert into course (course_num,dept_code,title,credits) values ('SZD277','6881','amet consectetuer adipiscing',1);
insert into course (course_num,dept_code,title,credits) values ('XDN211','4138','donec ut',2);
insert into course (course_num,dept_code,title,credits) values ('VJD160','5294','tellus in sagittis',2);
insert into course (course_num,dept_code,title,credits) values ('AQK956','5294','diam erat fermentum',2);
insert into course (course_num,dept_code,title,credits) values ('PNT267','5294','tincidunt in leo',4);
insert into course (course_num,dept_code,title,credits) values ('MGQ663','8946','convallis morbi odio',2);
insert into course (course_num,dept_code,title,credits) values ('LDC119','3448','duis consequat',4);
insert into course (course_num,dept_code,title,credits) values ('AWE736','0393','primis in',4);
insert into course (course_num,dept_code,title,credits) values ('LTQ018','3106','augue vel accumsan',5);
insert into course (course_num,dept_code,title,credits) values ('BYA627','3952','pede lobortis ligula',1);
insert into course (course_num,dept_code,title,credits) values ('AEX398','4510','vestibulum velit',2);
insert into course (course_num,dept_code,title,credits) values ('KZQ612','3106','sit amet sem',4);
insert into course (course_num,dept_code,title,credits) values ('JYG551','4510','lectus vestibulum',5);
insert into course (course_num,dept_code,title,credits) values ('QQM974','6881','fusce',5);
insert into course (course_num,dept_code,title,credits) values ('JUN888','2250','faucibus',1);
insert into course (course_num,dept_code,title,credits) values ('VCB800','3952','elementum',4);
insert into course (course_num,dept_code,title,credits) values ('GTK776','1849','ipsum primis',1);
insert into course (course_num,dept_code,title,credits) values ('ERK323','6857','metus arcu adipiscing',1);
insert into course (course_num,dept_code,title,credits) values ('HAL149','3106','et',2);
insert into course (course_num,dept_code,title,credits) values ('ZOY144','1300','lorem',1);
insert into course (course_num,dept_code,title,credits) values ('NWZ925','5294','mauris eget',3);
insert into course (course_num,dept_code,title,credits) values ('XQN729','1849','iaculis justo',4);
insert into course (course_num,dept_code,title,credits) values ('YLW690','0078','phasellus',1);
insert into course (course_num,dept_code,title,credits) values ('VGO073','8946','pede venenatis',3);
insert into course (course_num,dept_code,title,credits) values ('OTW194','1300','ante ipsum primis',3);
insert into course (course_num,dept_code,title,credits) values ('DBG948','2250','vitae',2);
insert into course (course_num,dept_code,title,credits) values ('CUP040','6881','integer',5);
insert into course (course_num,dept_code,title,credits) values ('LYT912','1849','penatibus et magnis',3);
insert into course (course_num,dept_code,title,credits) values ('PHB707','5294','justo sollicitudin ut',3);
insert into course (course_num,dept_code,title,credits) values ('WEN525','1300','nulla pede ullamcorper',2);
insert into course (course_num,dept_code,title,credits) values ('YQE037','3952','ipsum integer a',1);
insert into course (course_num,dept_code,title,credits) values ('GRM510','1300','quam pharetra magna',2);
insert into course (course_num,dept_code,title,credits) values ('ODH351','1465','nulla',1);
insert into course (course_num,dept_code,title,credits) values ('YJO018','1681','proin',4);
insert into course (course_num,dept_code,title,credits) values ('RJZ266','1849','aliquam non',2);
insert into course (course_num,dept_code,title,credits) values ('QJT685','3952','cursus',5);
insert into course (course_num,dept_code,title,credits) values ('BIE223','1681','in',1);
insert into course (course_num,dept_code,title,credits) values ('ERG296','0393','justo eu',4);
insert into course (course_num,dept_code,title,credits) values ('WNL351','0393','nulla',5);
insert into course (course_num,dept_code,title,credits) values ('QGK336','0078','felis sed',4);
insert into course (course_num,dept_code,title,credits) values ('UTY865','4138','mauris non',2);
insert into course (course_num,dept_code,title,credits) values ('PKG233','1849','gravida',3);
insert into course (course_num,dept_code,title,credits) values ('WXV677','6857','tellus',3);
insert into course (course_num,dept_code,title,credits) values ('KPC416','5294','vestibulum ante',2);
insert into course (course_num,dept_code,title,credits) values ('QIX309','0078','ut',5);
insert into course (course_num,dept_code,title,credits) values ('RLR295','0393','tempus',3);
insert into course (course_num,dept_code,title,credits) values ('MEO514','8946','donec ut',5);
insert into course (course_num,dept_code,title,credits) values ('MMQ140','4138','fusce lacus',5);
insert into course (course_num,dept_code,title,credits) values ('YLI680','4510','condimentum',2);
insert into course (course_num,dept_code,title,credits) values ('YOO618','6881','maecenas tincidunt',1);
insert into course (course_num,dept_code,title,credits) values ('RDW126','3952','et magnis dis',1);
insert into course (course_num,dept_code,title,credits) values ('YEC713','0393','adipiscing elit',3);
insert into course (course_num,dept_code,title,credits) values ('RPR458','3952','orci eget',4);
insert into course (course_num,dept_code,title,credits) values ('OLM017','1465','ut rhoncus',2);
insert into course (course_num,dept_code,title,credits) values ('WFZ093','8946','bibendum felis sed',1);
insert into course (course_num,dept_code,title,credits) values ('UEZ566','3106','purus',5);
insert into course (course_num,dept_code,title,credits) values ('NJM778','1465','amet justo',3);
insert into course (course_num,dept_code,title,credits) values ('FAO108','6857','sapien iaculis congue',4);
insert into course (course_num,dept_code,title,credits) values ('DYN965','4510','sed ante vivamus',5);
insert into course (course_num,dept_code,title,credits) values ('QRF582','6857','habitasse platea dictumst',5);
insert into course (course_num,dept_code,title,credits) values ('VSS596','1849','morbi vel',1);
insert into course (course_num,dept_code,title,credits) values ('WCZ531','5294','in consequat',3);
insert into course (course_num,dept_code,title,credits) values ('OOQ876','5294','a suscipit',4);
insert into course (course_num,dept_code,title,credits) values ('SVH415','3106','eu',4);
insert into course (course_num,dept_code,title,credits) values ('EQN175','1681','nisi',4);
insert into course (course_num,dept_code,title,credits) values ('YBC652','3106','nulla nunc',3);
insert into course (course_num,dept_code,title,credits) values ('TCF896','3952','sapien varius',3);
insert into course (course_num,dept_code,title,credits) values ('BJF336','4510','quam pede',2);
insert into course (course_num,dept_code,title,credits) values ('ZQE279','6881','eu nibh',2);
insert into course (course_num,dept_code,title,credits) values ('UHB133','3106','elementum eu',2);
insert into course (course_num,dept_code,title,credits) values ('KET809','1300','eget rutrum at',2);
insert into course (course_num,dept_code,title,credits) values ('VIC109','0078','in tempus sit',4);
insert into course (course_num,dept_code,title,credits) values ('XTO431','3448','orci nullam',3);
insert into course (course_num,dept_code,title,credits) values ('XWH704','0078','ac',4);
insert into course (course_num,dept_code,title,credits) values ('TBP936','4510','porta volutpat',3);
insert into course (course_num,dept_code,title,credits) values ('ICO544','6857','facilisi',3);
insert into course (course_num,dept_code,title,credits) values ('NUH862','4138','ipsum primis',5);
insert into course (course_num,dept_code,title,credits) values ('QWZ543','4138','praesent lectus vestibulum',2);
insert into course (course_num,dept_code,title,credits) values ('OTP835','2250','nam congue',2);
insert into course (course_num,dept_code,title,credits) values ('FWR639','1300','lorem vitae mattis',5);
