insert into dept_course (course_num,dept_code,title,credits) values ('BRI306','0078','nonummy maecenas',5);
insert into dept_course (course_num,dept_code,title,credits) values ('LTQ006','0078','lobortis',5);
insert into dept_course (course_num,dept_code,title,credits) values ('OZU974','2250','fusce congue diam',3);
insert into dept_course (course_num,dept_code,title,credits) values ('DXQ633','1300','amet eros suspendisse',5);
insert into dept_course (course_num,dept_code,title,credits) values ('MVF839','1465','cum sociis natoque',4);
insert into dept_course (course_num,dept_code,title,credits) values ('EPG843','3952','quam nec',4);
insert into dept_course (course_num,dept_code,title,credits) values ('MKJ441','8946','id',3);
insert into dept_course (course_num,dept_code,title,credits) values ('KKO305','1849','ultrices posuere cubilia',2);
insert into dept_course (course_num,dept_code,title,credits) values ('PPC248','0393','suspendisse potenti',2);
insert into dept_course (course_num,dept_code,title,credits) values ('STR413','8946','hac',4);
insert into dept_course (course_num,dept_code,title,credits) values ('OLM203','6881','elit proin',3);
insert into dept_course (course_num,dept_code,title,credits) values ('EPW314','5294','id lobortis convallis',5);
insert into dept_course (course_num,dept_code,title,credits) values ('LMH532','1300','posuere cubilia curae',1);
insert into dept_course (course_num,dept_code,title,credits) values ('JVG569','6857','sed',1);
insert into dept_course (course_num,dept_code,title,credits) values ('XRX934','0393','nisi eu orci',4);
insert into dept_course (course_num,dept_code,title,credits) values ('MNU873','3106','accumsan',5);
insert into dept_course (course_num,dept_code,title,credits) values ('YSO505','4138','ligula pellentesque ultrices',4);
insert into dept_course (course_num,dept_code,title,credits) values ('FGW555','8946','tellus',2);
insert into dept_course (course_num,dept_code,title,credits) values ('UFC982','1849','nibh in quis',4);
insert into dept_course (course_num,dept_code,title,credits) values ('QUC181','3106','integer pede',2);
insert into dept_course (course_num,dept_code,title,credits) values ('SZD277','4510','amet consectetuer adipiscing',1);
insert into dept_course (course_num,dept_code,title,credits) values ('XDN211','2250','donec ut',2);
insert into dept_course (course_num,dept_code,title,credits) values ('VJD160','4138','tellus in sagittis',2);
insert into dept_course (course_num,dept_code,title,credits) values ('AQK956','1849','diam erat fermentum',2);
insert into dept_course (course_num,dept_code,title,credits) values ('PNT267','6857','tincidunt in leo',4);
insert into dept_course (course_num,dept_code,title,credits) values ('MGQ663','1849','convallis morbi odio',2);
insert into dept_course (course_num,dept_code,title,credits) values ('LDC119','1681','duis consequat',4);
insert into dept_course (course_num,dept_code,title,credits) values ('AWE736','0393','primis in',4);
insert into dept_course (course_num,dept_code,title,credits) values ('LTQ018','6881','augue vel accumsan',5);
insert into dept_course (course_num,dept_code,title,credits) values ('BYA627','1849','pede lobortis ligula',1);
insert into dept_course (course_num,dept_code,title,credits) values ('AEX398','0393','vestibulum velit',2);
insert into dept_course (course_num,dept_code,title,credits) values ('KZQ612','0393','sit amet sem',4);
insert into dept_course (course_num,dept_code,title,credits) values ('JYG551','3448','lectus vestibulum',5);
insert into dept_course (course_num,dept_code,title,credits) values ('QQM974','1465','fusce',5);
insert into dept_course (course_num,dept_code,title,credits) values ('JUN888','3952','faucibus',1);
insert into dept_course (course_num,dept_code,title,credits) values ('VCB800','5294','elementum',4);
insert into dept_course (course_num,dept_code,title,credits) values ('GTK776','1681','ipsum primis',1);
insert into dept_course (course_num,dept_code,title,credits) values ('ERK323','3448','metus arcu adipiscing',1);
insert into dept_course (course_num,dept_code,title,credits) values ('HAL149','0078','et',2);
insert into dept_course (course_num,dept_code,title,credits) values ('ZOY144','3952','lorem',1);
insert into dept_course (course_num,dept_code,title,credits) values ('NWZ925','1849','mauris eget',3);
insert into dept_course (course_num,dept_code,title,credits) values ('XQN729','3106','iaculis justo',4);
insert into dept_course (course_num,dept_code,title,credits) values ('YLW690','5294','phasellus',1);
insert into dept_course (course_num,dept_code,title,credits) values ('VGO073','1681','pede venenatis',3);
insert into dept_course (course_num,dept_code,title,credits) values ('OTW194','8946','ante ipsum primis',3);
insert into dept_course (course_num,dept_code,title,credits) values ('DBG948','1465','vitae',2);
insert into dept_course (course_num,dept_code,title,credits) values ('CUP040','0393','integer',5);
insert into dept_course (course_num,dept_code,title,credits) values ('LYT912','6857','penatibus et magnis',3);
insert into dept_course (course_num,dept_code,title,credits) values ('PHB707','8946','justo sollicitudin ut',3);
insert into dept_course (course_num,dept_code,title,credits) values ('WEN525','6857','nulla pede ullamcorper',2);
insert into dept_course (course_num,dept_code,title,credits) values ('YQE037','1681','ipsum integer a',1);
insert into dept_course (course_num,dept_code,title,credits) values ('GRM510','0078','quam pharetra magna',2);
insert into dept_course (course_num,dept_code,title,credits) values ('ODH351','1681','nulla',1);
insert into dept_course (course_num,dept_code,title,credits) values ('YJO018','0078','proin',4);
insert into dept_course (course_num,dept_code,title,credits) values ('RJZ266','3106','aliquam non',2);
insert into dept_course (course_num,dept_code,title,credits) values ('QJT685','2250','cursus',5);
insert into dept_course (course_num,dept_code,title,credits) values ('BIE223','5294','in',1);
insert into dept_course (course_num,dept_code,title,credits) values ('ERG296','6857','justo eu',4);
insert into dept_course (course_num,dept_code,title,credits) values ('WNL351','4138','nulla',5);
insert into dept_course (course_num,dept_code,title,credits) values ('QGK336','6857','felis sed',4);
insert into dept_course (course_num,dept_code,title,credits) values ('UTY865','0078','mauris non',2);
insert into dept_course (course_num,dept_code,title,credits) values ('PKG233','4138','gravida',3);
insert into dept_course (course_num,dept_code,title,credits) values ('WXV677','3106','tellus',3);
insert into dept_course (course_num,dept_code,title,credits) values ('KPC416','5294','vestibulum ante',2);
insert into dept_course (course_num,dept_code,title,credits) values ('QIX309','3952','ut',5);
insert into dept_course (course_num,dept_code,title,credits) values ('RLR295','3106','tempus',3);
insert into dept_course (course_num,dept_code,title,credits) values ('MEO514','6881','donec ut',5);
insert into dept_course (course_num,dept_code,title,credits) values ('MMQ140','8946','fusce lacus',5);
insert into dept_course (course_num,dept_code,title,credits) values ('YLI680','6881','condimentum',2);
insert into dept_course (course_num,dept_code,title,credits) values ('YOO618','4510','maecenas tincidunt',1);
insert into dept_course (course_num,dept_code,title,credits) values ('RDW126','3952','et magnis dis',1);
insert into dept_course (course_num,dept_code,title,credits) values ('YEC713','3448','adipiscing elit',3);
insert into dept_course (course_num,dept_code,title,credits) values ('RPR458','0078','orci eget',4);
insert into dept_course (course_num,dept_code,title,credits) values ('OLM017','6881','ut rhoncus',2);
insert into dept_course (course_num,dept_code,title,credits) values ('WFZ093','3448','bibendum felis sed',1);
insert into dept_course (course_num,dept_code,title,credits) values ('UEZ566','2250','purus',5);
insert into dept_course (course_num,dept_code,title,credits) values ('NJM778','5294','amet justo',3);
insert into dept_course (course_num,dept_code,title,credits) values ('FAO108','8946','sapien iaculis congue',4);
insert into dept_course (course_num,dept_code,title,credits) values ('DYN965','6881','sed ante vivamus',5);
insert into dept_course (course_num,dept_code,title,credits) values ('QRF582','6881','habitasse platea dictumst',5);
insert into dept_course (course_num,dept_code,title,credits) values ('VSS596','5294','morbi vel',1);
insert into dept_course (course_num,dept_code,title,credits) values ('WCZ531','4138','in consequat',3);
insert into dept_course (course_num,dept_code,title,credits) values ('OOQ876','3448','a suscipit',4);
insert into dept_course (course_num,dept_code,title,credits) values ('SVH415','0078','eu',4);
insert into dept_course (course_num,dept_code,title,credits) values ('EQN175','4138','nisi',4);
insert into dept_course (course_num,dept_code,title,credits) values ('YBC652','3952','nulla nunc',3);
insert into dept_course (course_num,dept_code,title,credits) values ('TCF896','0078','sapien varius',3);
insert into dept_course (course_num,dept_code,title,credits) values ('BJF336','1681','quam pede',2);
insert into dept_course (course_num,dept_code,title,credits) values ('ZQE279','1681','eu nibh',2);
insert into dept_course (course_num,dept_code,title,credits) values ('UHB133','2250','elementum eu',2);
insert into dept_course (course_num,dept_code,title,credits) values ('KET809','4510','eget rutrum at',2);
insert into dept_course (course_num,dept_code,title,credits) values ('VIC109','8946','in tempus sit',4);
insert into dept_course (course_num,dept_code,title,credits) values ('XTO431','3952','orci nullam',3);
insert into dept_course (course_num,dept_code,title,credits) values ('XWH704','3106','ac',4);
insert into dept_course (course_num,dept_code,title,credits) values ('TBP936','1465','porta volutpat',3);
insert into dept_course (course_num,dept_code,title,credits) values ('ICO544','3952','facilisi',3);
insert into dept_course (course_num,dept_code,title,credits) values ('NUH862','8946','ipsum primis',5);
insert into dept_course (course_num,dept_code,title,credits) values ('QWZ543','2250','praesent lectus vestibulum',2);
insert into dept_course (course_num,dept_code,title,credits) values ('OTP835','3106','nam congue',2);
insert into dept_course (course_num,dept_code,title,credits) values ('FWR639','5294','lorem vitae mattis',5);
