insert into major (major_num,description,dept_code) values (1100,'GENERAL AGRICULTURE','5294');
insert into major (major_num,description,dept_code) values (1101,'AGRICULTURE PRODUCTION AND MANAGEMENT','5294');
insert into major (major_num,description,dept_code) values (1102,'AGRICULTURAL ECONOMICS','5294');
insert into major (major_num,description,dept_code) values (1103,'ANIMAL SCIENCES','5294');
insert into major (major_num,description,dept_code) values (1104,'FOOD SCIENCE','5294');
insert into major (major_num,description,dept_code) values (1105,'PLANT SCIENCE AND AGRONOMY','5294');
insert into major (major_num,description,dept_code) values (1106,'SOIL SCIENCE','5294');
insert into major (major_num,description,dept_code) values (1199,'MISCELLANEOUS AGRICULTURE','5294');
insert into major (major_num,description,dept_code) values (1301,'ENVIRONMENTAL SCIENCE','0078');
insert into major (major_num,description,dept_code) values (1302,'FORESTRY','5294');
insert into major (major_num,description,dept_code) values (1303,'NATURAL RESOURCES MANAGEMENT','5294');
insert into major (major_num,description,dept_code) values (1401,'ARCHITECTURE','4138');
insert into major (major_num,description,dept_code) values (1501,'AREA ETHNIC AND CIVILIZATION STUDIES','1681');
insert into major (major_num,description,dept_code) values (1901,'COMMUNICATIONS','0393');
insert into major (major_num,description,dept_code) values (1902,'JOURNALISM','0393');
insert into major (major_num,description,dept_code) values (1903,'MASS MEDIA','0393');
insert into major (major_num,description,dept_code) values (1904,'ADVERTISING AND PUBLIC RELATIONS','0393');
insert into major (major_num,description,dept_code) values (2001,'COMMUNICATION TECHNOLOGIES','3952');
insert into major (major_num,description,dept_code) values (2100,'COMPUTER AND INFORMATION SYSTEMS','3952');
insert into major (major_num,description,dept_code) values (2101,'COMPUTER PROGRAMMING AND DATA PROCESSING','3952');
insert into major (major_num,description,dept_code) values (2102,'COMPUTER SCIENCE','3952');
insert into major (major_num,description,dept_code) values (2105,'INFORMATION SCIENCES','3952');
insert into major (major_num,description,dept_code) values (2106,'COMPUTER ADMINISTRATION MANAGEMENT AND SECURITY','3952');
insert into major (major_num,description,dept_code) values (2107,'COMPUTER NETWORKING AND TELECOMMUNICATIONS','3952');
insert into major (major_num,description,dept_code) values (2201,'COSMETOLOGY SERVICES AND CULINARY ARTS','8946');
insert into major (major_num,description,dept_code) values (2300,'GENERAL EDUCATION','6857');
insert into major (major_num,description,dept_code) values (2301,'EDUCATIONAL ADMINISTRATION AND SUPERVISION','6857');
insert into major (major_num,description,dept_code) values (2303,'SCHOOL STUDENT COUNSELING','6857');
insert into major (major_num,description,dept_code) values (2304,'ELEMENTARY EDUCATION','6857');
insert into major (major_num,description,dept_code) values (2305,'MATHEMATICS TEACHER EDUCATION','6857');
insert into major (major_num,description,dept_code) values (2306,'PHYSICAL AND HEALTH EDUCATION TEACHING','6857');
insert into major (major_num,description,dept_code) values (2307,'EARLY CHILDHOOD EDUCATION','6857');
insert into major (major_num,description,dept_code) values (2308,'SCIENCE AND COMPUTER TEACHER EDUCATION','6857');
insert into major (major_num,description,dept_code) values (2309,'SECONDARY TEACHER EDUCATION','6857');
insert into major (major_num,description,dept_code) values (2310,'SPECIAL NEEDS EDUCATION','6857');
insert into major (major_num,description,dept_code) values (2311,'SOCIAL SCIENCE OR HISTORY TEACHER EDUCATION','6857');
insert into major (major_num,description,dept_code) values (2312,'TEACHER EDUCATION: MULTIPLE LEVELS','6857');
insert into major (major_num,description,dept_code) values (2313,'LANGUAGE AND DRAMA EDUCATION','6857');
insert into major (major_num,description,dept_code) values (2314,'ART AND MUSIC EDUCATION','6857');
insert into major (major_num,description,dept_code) values (2399,'MISCELLANEOUS EDUCATION','6857');
insert into major (major_num,description,dept_code) values (2400,'GENERAL ENGINEERING','4138');
insert into major (major_num,description,dept_code) values (2401,'AEROSPACE ENGINEERING','4138');
insert into major (major_num,description,dept_code) values (2402,'BIOLOGICAL ENGINEERING','4138');
insert into major (major_num,description,dept_code) values (2403,'ARCHITECTURAL ENGINEERING','4138');
insert into major (major_num,description,dept_code) values (2404,'BIOMEDICAL ENGINEERING','4138');
insert into major (major_num,description,dept_code) values (2405,'CHEMICAL ENGINEERING','4138');
insert into major (major_num,description,dept_code) values (2406,'CIVIL ENGINEERING','4138');
insert into major (major_num,description,dept_code) values (2407,'COMPUTER ENGINEERING','4138');
insert into major (major_num,description,dept_code) values (2408,'ELECTRICAL ENGINEERING','4138');
insert into major (major_num,description,dept_code) values (2409,'ENGINEERING MECHANICS PHYSICS AND SCIENCE','4138');
insert into major (major_num,description,dept_code) values (2410,'ENVIRONMENTAL ENGINEERING','4138');
insert into major (major_num,description,dept_code) values (2411,'GEOLOGICAL AND GEOPHYSICAL ENGINEERING','4138');
insert into major (major_num,description,dept_code) values (2412,'INDUSTRIAL AND MANUFACTURING ENGINEERING','4138');
insert into major (major_num,description,dept_code) values (2413,'MATERIALS ENGINEERING AND MATERIALS SCIENCE','4138');
insert into major (major_num,description,dept_code) values (2414,'MECHANICAL ENGINEERING','4138');
insert into major (major_num,description,dept_code) values (2415,'METALLURGICAL ENGINEERING','4138');
insert into major (major_num,description,dept_code) values (2416,'MINING AND MINERAL ENGINEERING','4138');
insert into major (major_num,description,dept_code) values (2417,'NAVAL ARCHITECTURE AND MARINE ENGINEERING','4138');
insert into major (major_num,description,dept_code) values (2418,'NUCLEAR ENGINEERING','4138');
insert into major (major_num,description,dept_code) values (2419,'PETROLEUM ENGINEERING','4138');
insert into major (major_num,description,dept_code) values (2499,'MISCELLANEOUS ENGINEERING','4138');
insert into major (major_num,description,dept_code) values (2500,'ENGINEERING TECHNOLOGIES','4138');
insert into major (major_num,description,dept_code) values (2501,'ENGINEERING AND INDUSTRIAL MANAGEMENT','4138');
insert into major (major_num,description,dept_code) values (2502,'ELECTRICAL ENGINEERING TECHNOLOGY','4138');
insert into major (major_num,description,dept_code) values (2503,'INDUSTRIAL PRODUCTION TECHNOLOGIES','4138');
insert into major (major_num,description,dept_code) values (2504,'MECHANICAL ENGINEERING RELATED TECHNOLOGIES','4138');
insert into major (major_num,description,dept_code) values (2599,'MISCELLANEOUS ENGINEERING TECHNOLOGIES','4138');
insert into major (major_num,description,dept_code) values (2601,'LINGUISTICS AND COMPARATIVE LANGUAGE AND LITERATURE','1681');
insert into major (major_num,description,dept_code) values (2602,'FRENCH GERMAN LATIN AND OTHER COMMON FOREIGN LANGUAGE STUDIES','1681');
insert into major (major_num,description,dept_code) values (2603,'OTHER FOREIGN LANGUAGES','1681');
insert into major (major_num,description,dept_code) values (2901,'FAMILY AND CONSUMER SCIENCES','8946');
insert into major (major_num,description,dept_code) values (3201,'COURT REPORTING','1465');
insert into major (major_num,description,dept_code) values (3202,'PRE-LAW AND LEGAL STUDIES','1465');
insert into major (major_num,description,dept_code) values (3301,'ENGLISH LANGUAGE AND LITERATURE','1681');
insert into major (major_num,description,dept_code) values (3302,'COMPOSITION AND RHETORIC','1681');
insert into major (major_num,description,dept_code) values (3401,'LIBERAL ARTS','1681');
insert into major (major_num,description,dept_code) values (3402,'HUMANITIES','1681');
insert into major (major_num,description,dept_code) values (3501,'LIBRARY SCIENCE','6857');
insert into major (major_num,description,dept_code) values (3600,'BIOLOGY','0078');
insert into major (major_num,description,dept_code) values (3601,'BIOCHEMICAL SCIENCES','0078');
insert into major (major_num,description,dept_code) values (3602,'BOTANY','0078');
insert into major (major_num,description,dept_code) values (3603,'MOLECULAR BIOLOGY','0078');
insert into major (major_num,description,dept_code) values (3604,'ECOLOGY','0078');
insert into major (major_num,description,dept_code) values (3605,'GENETICS','0078');
insert into major (major_num,description,dept_code) values (3606,'MICROBIOLOGY','0078');
insert into major (major_num,description,dept_code) values (3607,'PHARMACOLOGY','0078');
insert into major (major_num,description,dept_code) values (3608,'PHYSIOLOGY','0078');
insert into major (major_num,description,dept_code) values (3609,'ZOOLOGY','0078');
insert into major (major_num,description,dept_code) values (3611,'NEUROSCIENCE','0078');
insert into major (major_num,description,dept_code) values (3699,'MISCELLANEOUS BIOLOGY','0078');
insert into major (major_num,description,dept_code) values (3700,'MATHEMATICS','3952');
insert into major (major_num,description,dept_code) values (3701,'APPLIED MATHEMATICS','3952');
insert into major (major_num,description,dept_code) values (3702,'STATISTICS AND DECISION SCIENCE','3952');
insert into major (major_num,description,dept_code) values (3801,'MILITARY TECHNOLOGIES','8946');
insert into major (major_num,description,dept_code) values (4000,'MULTI/INTERDISCIPLINARY STUDIES','1849');
insert into major (major_num,description,dept_code) values (4001,'INTERCULTURAL AND INTERNATIONAL STUDIES','1681');
insert into major (major_num,description,dept_code) values (4002,'NUTRITION SCIENCES','1300');
insert into major (major_num,description,dept_code) values (4005,'MATHEMATICS AND COMPUTER SCIENCE','3952');
insert into major (major_num,description,dept_code) values (4006,'COGNITIVE SCIENCE AND BIOPSYCHOLOGY','0078');
insert into major (major_num,description,dept_code) values (4007,'INTERDISCIPLINARY SOCIAL SCIENCES','2250');
insert into major (major_num,description,dept_code) values (4101,'PHYSICAL FITNESS PARKS RECREATION AND LEISURE','8946');
insert into major (major_num,description,dept_code) values (4801,'PHILOSOPHY AND RELIGIOUS STUDIES','1681');
insert into major (major_num,description,dept_code) values (4901,'THEOLOGY AND RELIGIOUS VOCATIONS','1681');
insert into major (major_num,description,dept_code) values (5000,'PHYSICAL SCIENCES','4510');
insert into major (major_num,description,dept_code) values (5001,'ASTRONOMY AND ASTROPHYSICS','4510');
insert into major (major_num,description,dept_code) values (5002,'ATMOSPHERIC SCIENCES AND METEOROLOGY','4510');
insert into major (major_num,description,dept_code) values (5003,'CHEMISTRY','4510');
insert into major (major_num,description,dept_code) values (5004,'GEOLOGY AND EARTH SCIENCE','4510');
insert into major (major_num,description,dept_code) values (5005,'GEOSCIENCES','4510');
insert into major (major_num,description,dept_code) values (5006,'OCEANOGRAPHY','4510');
insert into major (major_num,description,dept_code) values (5007,'PHYSICS','4510');
insert into major (major_num,description,dept_code) values (5008,'MATERIALS SCIENCE','4138');
insert into major (major_num,description,dept_code) values (5098,'MULTI-DISCIPLINARY OR GENERAL SCIENCE','4510');
insert into major (major_num,description,dept_code) values (5102,'NUCLEAR, INDUSTRIAL RADIOLOGY, AND BIOLOGICAL TECHNOLOGIES','4510');
insert into major (major_num,description,dept_code) values (5200,'PSYCHOLOGY','6881');
insert into major (major_num,description,dept_code) values (5201,'EDUCATIONAL PSYCHOLOGY','6881');
insert into major (major_num,description,dept_code) values (5202,'CLINICAL PSYCHOLOGY','6881');
insert into major (major_num,description,dept_code) values (5203,'COUNSELING PSYCHOLOGY','6881');
insert into major (major_num,description,dept_code) values (5205,'INDUSTRIAL AND ORGANIZATIONAL PSYCHOLOGY','6881');
insert into major (major_num,description,dept_code) values (5206,'SOCIAL PSYCHOLOGY','6881');
insert into major (major_num,description,dept_code) values (5299,'MISCELLANEOUS PSYCHOLOGY','6881');
insert into major (major_num,description,dept_code) values (5301,'CRIMINAL JUSTICE AND FIRE PROTECTION','1465');
insert into major (major_num,description,dept_code) values (5401,'PUBLIC ADMINISTRATION','1465');
insert into major (major_num,description,dept_code) values (5402,'PUBLIC POLICY','1465');
insert into major (major_num,description,dept_code) values (5403,'HUMAN SERVICES AND COMMUNITY ORGANIZATION','6881');
insert into major (major_num,description,dept_code) values (5404,'SOCIAL WORK','6881');
insert into major (major_num,description,dept_code) values (5500,'GENERAL SOCIAL SCIENCES','2250');
insert into major (major_num,description,dept_code) values (5501,'ECONOMICS','2250');
insert into major (major_num,description,dept_code) values (5502,'ANTHROPOLOGY AND ARCHEOLOGY','1681');
insert into major (major_num,description,dept_code) values (5503,'CRIMINOLOGY','2250');
insert into major (major_num,description,dept_code) values (5504,'GEOGRAPHY','2250');
insert into major (major_num,description,dept_code) values (5505,'INTERNATIONAL RELATIONS','2250');
insert into major (major_num,description,dept_code) values (5506,'POLITICAL SCIENCE AND GOVERNMENT','2250');
insert into major (major_num,description,dept_code) values (5507,'SOCIOLOGY','2250');
insert into major (major_num,description,dept_code) values (5599,'MISCELLANEOUS SOCIAL SCIENCES','2250');
insert into major (major_num,description,dept_code) values (5601,'CONSTRUCTION SERVICES','8946');
insert into major (major_num,description,dept_code) values (5701,'ELECTRICAL, MECHANICAL, AND PRECISION TECHNOLOGIES AND PRODUCTION','8946');
insert into major (major_num,description,dept_code) values (5901,'TRANSPORTATION SCIENCES AND TECHNOLOGIES','8946');
insert into major (major_num,description,dept_code) values (6000,'FINE ARTS','3106');
insert into major (major_num,description,dept_code) values (6001,'DRAMA AND THEATER ARTS','3106');
insert into major (major_num,description,dept_code) values (6002,'MUSIC','3106');
insert into major (major_num,description,dept_code) values (6003,'VISUAL AND PERFORMING ARTS','3106');
insert into major (major_num,description,dept_code) values (6004,'COMMERCIAL ART AND GRAPHIC DESIGN','3106');
insert into major (major_num,description,dept_code) values (6005,'FILM VIDEO AND PHOTOGRAPHIC ARTS','3106');
insert into major (major_num,description,dept_code) values (6006,'ART HISTORY AND CRITICISM','1681');
insert into major (major_num,description,dept_code) values (6007,'STUDIO ARTS','3106');
insert into major (major_num,description,dept_code) values (6099,'MISCELLANEOUS FINE ARTS','3106');
insert into major (major_num,description,dept_code) values (6100,'GENERAL MEDICAL AND HEALTH SERVICES','1300');
insert into major (major_num,description,dept_code) values (6102,'COMMUNICATION DISORDERS SCIENCES AND SERVICES','1300');
insert into major (major_num,description,dept_code) values (6103,'HEALTH AND MEDICAL ADMINISTRATIVE SERVICES','1300');
insert into major (major_num,description,dept_code) values (6104,'MEDICAL ASSISTING SERVICES','1300');
insert into major (major_num,description,dept_code) values (6105,'MEDICAL TECHNOLOGIES TECHNICIANS','1300');
insert into major (major_num,description,dept_code) values (6106,'HEALTH AND MEDICAL PREPARATORY PROGRAMS','1300');
insert into major (major_num,description,dept_code) values (6107,'NURSING','1300');
insert into major (major_num,description,dept_code) values (6108,'PHARMACY PHARMACEUTICAL SCIENCES AND ADMINISTRATION','1300');
insert into major (major_num,description,dept_code) values (6109,'TREATMENT THERAPY PROFESSIONS','1300');
insert into major (major_num,description,dept_code) values (6110,'COMMUNITY AND PUBLIC HEALTH','1300');
insert into major (major_num,description,dept_code) values (6199,'MISCELLANEOUS HEALTH MEDICAL PROFESSIONS','1300');
insert into major (major_num,description,dept_code) values (6200,'GENERAL BUSINESS','3448');
insert into major (major_num,description,dept_code) values (6201,'ACCOUNTING','3448');
insert into major (major_num,description,dept_code) values (6202,'ACTUARIAL SCIENCE','3448');
insert into major (major_num,description,dept_code) values (6203,'BUSINESS MANAGEMENT AND ADMINISTRATION','3448');
insert into major (major_num,description,dept_code) values (6204,'OPERATIONS LOGISTICS AND E-COMMERCE','3448');
insert into major (major_num,description,dept_code) values (6205,'BUSINESS ECONOMICS','3448');
insert into major (major_num,description,dept_code) values (6206,'MARKETING AND MARKETING RESEARCH','3448');
insert into major (major_num,description,dept_code) values (6207,'FINANCE','3448');
insert into major (major_num,description,dept_code) values (6209,'HUMAN RESOURCES AND PERSONNEL MANAGEMENT','3448');
insert into major (major_num,description,dept_code) values (6210,'INTERNATIONAL BUSINESS','3448');
insert into major (major_num,description,dept_code) values (6211,'HOSPITALITY MANAGEMENT','3448');
insert into major (major_num,description,dept_code) values (6212,'MANAGEMENT INFORMATION SYSTEMS AND STATISTICS','3448');
insert into major (major_num,description,dept_code) values (6299,'MISCELLANEOUS BUSINESS & MEDICAL ADMINISTRATION','3448');
insert into major (major_num,description,dept_code) values (6402,'HISTORY','1681');
insert into major (major_num,description,dept_code) values (6403,'UNITED STATES HISTORY','1681');
